# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/select-top-image-models',
                'doc_host': 'https://geg00.github.io',
                'git_url': 'https://github.com/geg00/select-top-image-models',
                'lib_path': 'select_top_image_models'},
  'syms': {'select_top_image_models.core': {'select_top_image_models.core.foo': ('core.html#foo', 'select_top_image_models/core.py')}}}
